### ISSUE TITLE
New XCA v2.5.0 Fails to create certificates on Mac OS Monterey 12.7

### ISSUE THREAD

**Issue by SemoTech** [chris2511/xca#461] opened 2023-09-26 20:18 UTC
Hello, 
Seems the new XCA v2.5.0 for Mac OS fixes the PEM Chain export bug that created empty files, thank you!, but now certificates cannot be created! 

Private Keys get made but there is an error actually creating the certificate:   
![image](https://github.com/chris2511/xca/assets/1452100/e9d42a73-edd6-4182-b634-a479926987dd)
This is all with standard/default settings.

Running the App on Monterey 12.7
For reference, the previous XCA version 2.4.0 still works and has no issues creating certificates on the same Mac OS, just the chain export bug...

**Comment by chris2511** [comment] 2023-09-26 20:50
You are not alone. Duplicate of #458
Seems like I'm the only one who can **not** reproduce the issue ... 

Neither on MAC nor Windows nor Linux, which makes it really hard to debug.

**Closed by chris2511** 2023-09-26 20:50 UTC
