### ISSUE TITLE
digital envelope routines::unsupported algorithm when signing a certificate

### ISSUE THREAD

**Issue by monnerat** [chris2511/xca#410] opened 2023-01-24 14:21 UTC
With a recent git snapshot (dec 26, 2022), trying to sign a certificate always results in the following error:
```
The following error occurred:
(8pki_x509[]:essai)
error:0300009C:digital envelope routines::unsupported algorithm
error:068C0100:asn1 encoding routines::malloc failure
error:068C0100:asn1 encoding routines::malloc failure

(pki_x509.cpp:574)
```

This seems to be triggered by https://github.com/chris2511/xca/blob/2ba114d393e75a1a74ccde09fc9354d510813bd1/lib/pki_x509.cpp#L565-L577

This occurs for creation and also for renewal.

Signature algorithm used: SHA256
Key type: RSA 2048 bits.
OpenSSL version 3.0.5.
OS: Fedora 37.

Works like a charm with xca 2.4.0

**Comment by monnerat** [comment] 2023-05-24 18:50
> Could be related to and fixed by https://github.com/chris2511/xca/pull/425. Please try the latest release

Thanks for the hint. Unfortunately the problem is not fixed with a today's snapshot.

**Comment by chris2511** [comment] 2023-09-26 18:37
Duplicate of #458. Sadly I cannot reproduce it, but it seems to be severe.

**Closed by chris2511** 2023-09-26 18:37 UTC

**Comment by monnerat** [comment] 2023-10-06 16:27
The solution/workaround listed in https://github.com/chris2511/xca/discussions/468 works for me, many thanks for it.
Too bad there has'nt been an intermediate release proposing the password(s) reset while it was still working.
I'm adding a `README.IMPORTANT` doc file about it in the Fedora package, but users will only see it when 2.5.0 is already installed, unfortunately.
