### ISSUE TITLE
Error when signing a cert with ed25519

### ISSUE THREAD

**Issue by marek22k** [chris2511/xca#376] opened 2022-08-09 14:06 UTC
I try to create a self-signed certificate with a key of type ed25519, but get a error dialog:
```
The following error occurred:
error:0D06407A:asn1 encoding routines:a2d_ASN1_OBJECT:first num too large
```

**Comment by marek22k** [comment] 2022-08-09 14:14
maybe related: https://www.mail-archive.com/openssl-users@openssl.org/msg47463.html

**Comment by ya-isakov** [comment] 2022-08-30 10:56
I think, it's a duplicate of #321?

**Comment by marek22k** [comment] 2022-08-30 11:20
I would say only partially. I was able to create the ed25519 key, but not sign anything. In the other issue, as far as I read through it, not even a key could be generated.

**Comment by ya-isakov** [comment] 2022-08-30 11:23
@marek22k, hmm, it said, in #321, that key can be created - and that certificate cannot. It means, that it's also signing issue.

**Closed** 2022-08-30 15:42 UTC
