### ISSUE TITLE
Unable to use ENTER when renaming with keyboard

### ISSUE THREAD

**Issue by farosch** [chris2511/xca#158] opened 2020-01-29 18:27 UTC
Every so often when I rename a certificate I use F2 to enter edit mode.
After editing the name when I press enter it opens the certificate details instead and discardes my changes.

-> Pressing enter should not trigger the certificates detail window when editing a certificate name.

**Comment by chris2511** [comment] 2020-01-29 18:51
Duplicate of #101
Fixed with 3a39e4d for the next release

**Closed by chris2511** 2020-01-29 18:51 UTC
