### ISSUE TITLE
Attempting to import EC key causes application to stop responding

### ISSUE THREAD

**Issue by dryiceza** [chris2511/xca#262] opened 2021-03-12 01:22 UTC
Hi,

I created a new xca database and attempted to import an elliptic curve private key (no password set, secp224r1, secp384r1, secp521r1) that was created with OpenSSL outside of xca. As soon as I import it though, the application stops responding.

I'm running the Windows version 2.3.0 of the software.

Not sure how to troubleshoot this issue?

Let me know if you have any questions.

Thanks for a great product!
Nolan

**Comment by chris2511** [comment] 2021-04-01 10:30
Duplicate of #208

**Closed by chris2511** 2021-04-01 10:30 UTC
