### ISSUE TITLE
Freeze when generating DH

### ISSUE THREAD

**Issue by Onepamopa** [chris2511/xca#146] opened 2019-12-15 12:03 UTC
Version 2.1.2 freezes at 67% (not responding) when gerating 2048 bit DH.
After about 5-6 minutes, the file gets generated and I can save it.

Windows 10 64 bit

**Comment by chris2511** [comment] 2019-12-15 15:24
Duplicate of Issue #68, fixed for the next release

**Closed by chris2511** 2019-12-15 15:24 UTC
