### ISSUE TITLE
Can't connect remote database

### ISSUE THREAD

**Issue by imlison** [chris2511/xca#544] opened 2024-04-10 07:26 UTC
os: macos monterey 12.7.4
xca version: 2.6.0

I installed via brew
`brew install unixodbc libiodbc mariadb-connector-odbc`

and put odbc.ini in three places:
`~/.odbc.ini`
`/etc/odbc.ini`
`/usr/local/etc/odbc.ini`

the file content
```
[Default]
Description = MariaDB Driver
Driver = /usr/local/lib/mariadb/libmaodbc.dylib
#Driver = /usr/local/opt/libiodbc/lib/libiodbc.dylib
Server = 127.0.0.1
Database = xca
User = xca
Password = MY_PASSWORD
```

when test with isql, it connect success
`isql -v Default`

but it didn't work for xca
![1](https://github.com/chris2511/xca/assets/18003517/f7e22c52-9c05-4e3c-bd33-a9a519bfc2d0)
![2](https://github.com/chris2511/xca/assets/18003517/9103a539-a87d-4e3b-ac8a-de3823f79153)

Is it something wrong with my settings?

thanks

**Comment by chris2511** [comment] 2024-09-30 18:56
Duplicate of #537 and sadly no solution

**Closed by chris2511** 2024-09-30 18:56 UTC
