### ISSUE TITLE
PEM export with key

### ISSUE THREAD

**Issue by saho-tabakov** [chris2511/xca#472] opened 2023-10-06 09:21 UTC
Hi All,

Using XCA v.2.5.0, file export in "PEM+Key" format, exports only the certificate and no key, while using v.2.4.0 both the key and the certificate are exported.

Is this intended behavior or an issue?

Best Regards
Alex

**Comment by chris2511** [comment] 2023-10-06 09:25
Duplicate of #465
Fixed for the next release with 8f05c3eac9443b465f04b85fb336ad032b12391b

**Comment by saho-tabakov** [comment] 2023-10-06 11:47
Sorry, I didn't search through the closed issues.
10x

**Comment by Goodwu** [comment] 2023-10-24 04:03
<img width="557" alt="image" src="https://github.com/chris2511/xca/assets/348005/aaff9e75-06a0-4295-b33a-f6cb8fd841c9">
https://github.com/chris2511/xca/actions/runs/6516349216
Using the version here, the private key still cannot be exported anywhere.
The length of the private key file exported on the "Private Keys" tab is 0 bytes.
The file exported on the "Certificates" tab only has the certificate and no private key.

**Comment by Goodwu** [comment] 2023-11-04 12:39
@chris2511 Exporting private key still not work, please take a look.

**Comment by NSGrid** [comment] 2024-01-12 00:17
Similar story. Also, when I upgraded to version 2.5.0 I didn't export the private key in the PEM file, only the certificate itself. I rolled back to version 2.4.0 and everything worked again. I hope the developer will fix this glitch in the next official release of the program!

**Comment by chris2511** [comment] 2024-02-25 21:55
I did rebuild and test d36b32feac3d9a13545119c627684588030988e0 on Mac and it exports all keys and cers + key fine.

**Closed by chris2511** 2024-02-25 21:55 UTC
