### ISSUE TITLE
xca 2.1.1 crashes on macOS Mojave

### ISSUE THREAD

**Issue by MrSpock** [chris2511/xca#75] opened 2018-10-12 08:38 UTC
Application is crashing on current macOS Mojave (10.14):
```
Process:               xca [29089]
Path:                  /Volumes/*/xca.app/Contents/MacOS/xca
Identifier:            de.hohnstaedt.xca
Version:               2.1.1 (2.1.1)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           xca [29089]
User ID:               501

Date/Time:             2018-10-12 10:36:48.567 +0200
OS Version:            Mac OS X 10.14 (18A391)
Report Version:        12
Anonymous UUID:        BFC34C41-36C6-722A-B5D1-42651AC4E832

Sleep/Wake UUID:       B8DD51C1-AA0F-479A-9D84-CB101372BF26

Time Awake Since Boot: 120000 seconds
Time Since Wake:       380 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/QtGui.framework/Versions/5/QtGui
  Referenced from: /Volumes/*/xca.app/Contents/MacOS/xca
  Reason: image not found

Binary Images:
       0x105b54000 -        0x105d3ffff +de.hohnstaedt.xca (2.1.1 - 2.1.1) <C8286030-53E8-3884-877E-4A449E22F40F> /Volumes/*/xca.app/Contents/MacOS/xca
       0x105ddf000 -        0x105de7ff3 +libltdl.7.dylib (0) <F370338C-B56B-30DF-974C-BB4E713ED32A> /Volumes/*/xca.app/Contents/Frameworks/libltdl.7.dylib
       0x105e0a000 -        0x105ff63df +libcrypto.1.1.dylib (0) <722A5FAB-58DD-329D-9293-457ACDC5648D> /Volumes/*/xca.app/Contents/Frameworks/libcrypto.1.1.dylib
       0x1077f0000 -        0x10786e6a7  dyld (625.13) <D6387150-2FB8-3066-868D-72E1B1C43982> /usr/lib/dyld
```

**Comment by MrSpock** [comment] 2018-10-12 08:53
Looks like the same issuse is #69

**Comment by chris2511** [comment] 2018-10-13 07:00
I re-built the image and it seems to be OK:
```
chris$ otool -l /Volumes/xca-2.1.1/xca.app/Contents/MacOS/xca | grep -A3 LC_RPATH 
          cmd LC_RPATH
      cmdsize 48
         path @executable_path/../Frameworks (offset 12)
Load command 23
```
Please check: https://www.hohnstaedt.de/downloads/xca-2.1.1.dmg with sha256: `d376bba09657477a20b89b324154c7a76bd3360df37488153727f5d0861a857f` and report.

Thanks!

**Comment by chris2511** [comment] 2018-10-16 04:16
duplicate of #69

**Closed by chris2511** 2018-10-16 04:16 UTC
